### ISSUE TITLE
Does kustomize work?

### ISSUE THREAD

**Issue by dennybaa** [roboll/helmfile#1954] opened 2021-09-03 17:34 UTC
I have been trying jsonPatches and strategicMergePatches. Neither seems to work. For example:

the template

```
repositories:
- name: incubator
  url: https://charts.helm.sh/incubator

releases:
- name: raw1
  chart: incubator/raw
  values:
  - resources:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: raw1
        namespace: default
      data:
        foo: FOO
  strategicMergePatches:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: raw1
        namespace: default
      data:
        bar: BAR
```

renders into nothing and no configmap is ever deployed.
Does anyone have clarification on this? Thanks.

**Comment by yurrriq** [comment] 2021-09-13 16:42
At least `jsonPatches` works for me, with kustomize 3.8.1.

**Comment by eigood** [comment] 2021-09-13 22:22
I'm having this same problem too; kustomize 4.3.0, helmfile 0.139.9(tried 0.140.0), helm 3.7.0-rc3.

I have a local chart, with kustomize.yaml, that contains a single resource, a VirtualService for istio.  If I use a jsonPatch or a smp in helmfile, then the entire resource is not in /tmp/chartifyXXXX, and all.patched.resources.yaml is blank.

**Comment by eigood** [comment] 2021-09-13 22:31
The following 3 files showcase the bug.  There is no ConfigMap in the final output.  If you comment-out the SMP, then the ConfigMap will be applied.  Uncomment again, and the CM gets removed.

```yaml
# helmfile.yaml
releases:
  - name: helmfile-bug
    chart: ./bug-helmfile
    strategicMergePatches:
      - apiVersion: v1
        kind: ConfigMap
        metadata:
          name: helmfile-bug
        data:
          key: value
```
```yaml
# bug-helmfile/kustomization.yaml
resources:
  - ./config-map.yaml
```
```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: helmfile-bug
data:
  key: value
---
```

**Comment by eigood** [comment] 2021-09-13 22:37
I got to this point, as I was attempting to install kube-prometheus-stack(worked great last week), but then today was trying to write a jsonPatch that then added an envFrom to the grafana Deployment, so that I could have the latter make use of keycloak for oauth config.  

I then ran into the bug that was fixed in 0.139, that doing the previous produced an error that the dependent chart was not found.  And that then lead me to this problem.

**Comment by eigood** [comment] 2021-09-13 23:46
Reading https://github.com/variantdev/chartify/commit/55b23f9e9d43ae1105a536a659fa35f004806b2a#diff-57f6b83ec3544fa65e2b3e830eb15f5b5bf5f232bd1b488744c56bb303b9f64a

I don't really know Go, but based on what I'm reading, I think there is a bug when there is a *single* resource in the chart.  If I add a second dummy ConfigMap to my example, then I can patch one of them, or none of them, and both show up in all cases.

**Comment by eigood** [comment] 2021-09-13 23:54
So, in summary, the TLDR: A chart with a *single* resource can't be patched, but more than one resource can be.   Attempting to patch the single resource ends up not seeing the resource at all, based on the previously linked change.

**Comment by mumoshu** [comment] 2021-09-14 05:46
@eigood Thanks for your efforts! I believe https://github.com/roboll/helmfile/pull/1962 will fix the issue.

**Closed** 2021-09-14 05:48 UTC

**Comment by eigood** [comment] 2021-09-14 17:02
@mumoshu Confirmed, thank you!
