### ISSUE TITLE
evalsymlink failure chartify temp file reported as "no such file or directory" despite existing when using jsonPatches for adhoc

### ISSUE THREAD

**Issue by slalom25** [roboll/helmfile#1820] opened 2021-04-30 11:17 UTC
` helm version > Version:"v3.4.2"`
`kustomize version > Version:kustomize/v4.0.5`
`helmfile version >  v0.138.7`

helmfile_deployment.yaml:

```
                 ***

releases:
  - name: "coredns"            
    version: {{.Environment.Values | default (env "COREDNS_VERSION") | default ""}}   
    <<: *chartmuseum                                                                   
    jsonPatches:                                                                   
    - target:                                                                              
         group: apps                                                                         
         version: v1                                                                        
         kind: Deployment                                                                    
         name: coredns-coredns                                                           
      patch:                                                                               
        - op: add                                                                            
           path: /metadata/labels/hello                                                     
           value: "world"
        
                 ***      
```     

Error:

```
generated and using kustomization.yaml:                                             
kind: ""                                                                           
apiversion: ""                                                                      
resources:                                                                          
- templates/service-metrics.yaml                                                   
- templates/service.yaml                                                            
- templates/deployment.yaml                                                         
- templates/configmap.yaml                                                          
- templates/clusterrole.yaml                                                        
- templates/clusterrolebinding.yaml                                                 
patchesJson6902:                                                                    
- target:                                                                               
     group: apps                                                                         
     kind: Deployment                                                              
     name: coredns-coredns                                                          
     version: v1                                                                                                                                    
   path: jsonpatches/patch.0.yaml     

Generating /tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns/all.patched.yaml                                                                                   running kustomize build /tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns --output /tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns/all.patched.yaml   

Error: evalsymlink failure on '/tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns' : lstat /tmp/chartify251993839: no such file or directory                                                                                                         
Removed /tmp/helmfile653553803/coredns-coredns-values-5b9b657487                    
Removed /tmp/helmfile110841454/coredns-coredns-values-5b769778b7                    
Removed /tmp/helmfile474989301/coredns-coredns-values-8474674f96                    
Removed /tmp/helmfile115401680/coredns-coredns-values-58cc6c684                     
err: [exit status 1                                                                                                                                                     

COMMAND:                                                                              
kustomize build /tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns --output /tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns/all.patched.yaml                                                                                             

OUTPUT:                                                                               
Error: evalsymlink failure on '/tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns' : lstat /tmp/chartify251993839: no such file or directory]                  
in ./helmfile_deployment.yaml: [exit status 1                                                                                                                           

COMMAND:                                                                              
kustomize build /tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns --output /tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns/all.patched.yaml                                                                                             

OUTPUT:                                                                               
Error: evalsymlink failure on '/tmp/chartify251993839/coredns-coredns-6c6cdfbdd5/coredns' : lstat /tmp/chartify251993839: no such file or directory]  

```     

But

```
ls /tmp/chartify251993839

coredns-coredns-6c6cdfbdd5   
```     

Indicating that the missing file / directory is in-fact present...

**Comment by mumoshu** [comment] 2021-05-01 03:19
@slalom25 Hey! How did you install helm/helmfile/kustomize? Sharing outputs from `which helmfile`, `which helm`, `which kustomzie` would also be helpful.

I'm doubting if you're using snap to install any of them, which can be the source of problems like seen in https://github.com/actions/virtual-environments/issues/1540#issuecomment-688816605

**Comment by mumoshu** [comment] 2021-05-01 12:16
I'm closing this as answered/irrelevant to helmfile itself. But please feel free to reopen or submit another issue with reproduction steps if it actually turned out to be happening due to a bug in helmfile.

**Closed by mumoshu** 2021-05-01 12:16 UTC
Labels: invalid

**Comment by slalom25** [comment] 2021-05-03 15:10
@mumoshu Hi sorry for late response... You really hit the nail on the head with this one! I did as a matter of fact install kustomize through snap... I had to uninstall it and install it the way  they describe in https://kubectl.docs.kubernetes.io/installation/kustomize/binaries/ . All good now! Thank you for the help!

**Comment by mumoshu** [comment] 2021-05-05 01:43
@slalom25 Hey! Thanks for confirming. Glad to hear it worked. It was a good-to-know for me, too!

FWIW, I started not liking `snap` as I constantly see weird compatibility issues like this.

I had some issue even with `docker` installed via snap before :) It doesn't mount /tmp but somewhere else that breaks the usage from `kind` https://kind.sigs.k8s.io/docs/user/known-issues/#docker-installed-with-snap
