### ISSUE TITLE
Feature Request: Workflow to simplify upgrades

### ISSUE THREAD

**Issue by mikhailadvani** [roboll/helmfile#563] opened 2019-04-24 21:26 UTC
Background

We have a setup which involves several charts from the stable repo as well as self hosted repos. We would like to periodically update the charts in a convenient manner. 

Proposed Solution:

1. New flag --force-latest for apply and diff commands which would apply/diff the charts with the latest version (should ideally not be run with --skip-repo-update)
2. New subcommand freeze. Would populate the version number in helmfile.yaml/helmfile.d with what is installed in the cluster. Similar to a `pip freeze` functionality of python.

**Comment by mumoshu** [comment] 2019-05-05 03:50
@mikhailadvani Hey! Could this be a duplicate of https://github.com/roboll/helmfile/issues/483#issuecomment-475493523 / Can we discuss about this feature there?

**Comment by mumoshu** [comment] 2019-05-05 03:55
Notes: `--force-latest` could better be named `--dev` or `--force-dev-versions` to be consistent with helm's `--dev` flag.

Regarding 2, I've proposed `helmfile.lock.yaml` generated as part of `helm dependency update` in #483. Perhaps it can be updated via a command similar to `pip freeze` - `helmfile update`, `helmfile freeze`, etc?

**Comment by sstarcher** [comment] 2019-05-10 14:07
Yep, this looks like it fits well into the lockfile concept with a freeze(pip)/ensure(go dep) and update.

**Comment by mumoshu** [comment] 2019-05-14 09:05
#593 enhances `helmfile deps` for this use-case.

One thing to note:

> New flag --force-latest for apply and diff commands which would apply/diff the charts with the latest version (should ideally not be run with --skip-repo-update)

You should add version constraint to each release in the helmfile state file, like `version: > 1.5.0` if you want to avoid getting latest chart versions on `helmfile deps`.

**Closed** 2019-05-15 00:39 UTC
Labels: duplicate, feature request
