### ISSUE TITLE
Implement absent for deletion of charts

### ISSUE THREAD

**Issue by estahn** [roboll/helmfile#362] opened 2018-09-24 23:40 UTC
I would like to be able to define `absent` as part of a release in the helmfile. Upon `helmfile sync` all releases with `absent: true` will be deleted.

```
releases:
  - name: super-magician
    namespace: default
    chart: stable/prometheus-cloudwatch-exporter
    version: 0.2.0
    values:
      - prometheus-cloudwatch-exporter/values.yaml
    absent: true
```

**Comment by andytom** [comment] 2018-09-26 12:38
I think this is a duplicate of https://github.com/roboll/helmfile/issues/197.

**Comment by mumoshu** [comment] 2018-09-26 16:05
@andytom Thanks for chiming in! Yeah, this seems like a dup of #197.

@estahn Are we following you correctly? In case this is really a dup of #197, I'll close this as resolved after adding some doc.

**Comment by estahn** [comment] 2018-09-26 20:43
@andytom @mumoshu Ah, perfect. That is what I was looking for.

**Comment by mumoshu** [comment] 2018-09-26 23:30
@estahn Yeah, please! I'll close this via #371.

**Closed** 2018-09-27 02:17 UTC
Labels: documentation
