### ISSUE TITLE
error when selector does not match anything

### ISSUE THREAD

**Issue by sstarcher** [roboll/helmfile#164] opened 2018-06-11 19:40 UTC
If I run `helmfile -l name=bob sync` and we have no release named bob I would expect helmfile to exit with an error.  Currently it exists with a code of 0.

**Comment by mumoshu** [comment] 2018-06-12 00:29
Good catch! Thats should be fixed.

**Comment by lswith** [comment] 2018-07-17 00:34
I just encountered the opposite of this. If I have nothing that matches the selector, I would expect an error but I would also like to silence this or have a seperate error to the normal error.

Mainly I use helmfile in this way:
```
helmfile -f ./path/to/helmfile --selector state!=active delete
helmfile -f ./path/to/helmfile --selector state=active sync
```

This allows me to delete from code rather than manually. The problem is when there is nothing to delete, helmfile errors out. This should be a different error to when something is failing to delete.

**Comment by mumoshu** [comment] 2018-08-22 08:27
@lswith Good point!
Would an exit code of `2` suffice your need?

**Comment by mumoshu** [comment] 2018-08-22 08:28
@lswith Anyway, opened #219 for that.

**Comment by mumoshu** [comment] 2018-08-22 08:29
I'm closing this as the original issue has been resolved via #165

**Closed by mumoshu** 2018-08-22 08:28 UTC
Labels: enhancement, help wanted
