### ISSUE TITLE
`strategicMergePatches` seems to break CRDs

### ISSUE THREAD

**Issue by SohumB** [roboll/helmfile#2117] opened 2022-03-28 06:03 UTC
This is at least in v0.143.4, and is a regression from v0.143.0. If you have a chart that has CRDs and that has `strategicMergePatches` applied, and you're applying this against a cluster that already has said CRDs, you get something like this error:

```
COMMAND:
  kustomize build /tmp/sohum/chartify3067284263/monitoring/robusta/robusta --output /tmp/sohum/chartify3067284263/monitoring/robusta/robusta/all.patched.yaml

OUTPUT:
  Error: accumulating resources: accumulation err='accumulating resources from 'charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml': may not add resource with an already registered id: CustomResourceDefinition.v1.apiextensions.k8s.io/alertmanagers.monitoring.coreos.com.[noNs]': got file 'crd-alertmanagers.yaml', but '/tmp/sohum/chartify3067284263/monitoring/robusta/robusta/charts/kube-prometheus-stack/crds/crd-alertmanagers.yaml' must be a directory to be a root]
```

**Comment by mumoshu** [comment] 2022-03-28 06:22
@SohumB Thanks for reporting!

Would you mind sharing what's in the `/tmp/sohum/chartify3067284263/monitoring/robusta/robusta/kustomization.yaml` when it failed with `kustomize build /tmp/sohum/chartify3067284263/monitoring/robusta/robusta ...`?

(`chartify3067284263` part may differ between runs

**Comment by SohumB** [comment] 2022-03-28 06:30
Sure, I can hand you the [whole directory](https://drive.google.com/file/d/18dWO9PIfGLLRGSSwZkkfL65zCjJfglvW/view?usp=sharing).

**Comment by mumoshu** [comment] 2022-03-29 00:39
@SohumB Thanks! I was able to reproduce it and was confirmed that it doesn't occur after https://github.com/variantdev/chartify/pull/31, which I originally intended to fix another issue but apparently fixes your issue too. #2119 is the PR for Helmfile.

**Comment by mumoshu** [comment] 2022-03-29 01:00
@SohumB FYI, you'll shortly see v0.143.5 binaries available under the release page once https://app.circleci.com/pipelines/github/roboll/helmfile/1188/workflows/7dabe5a8-ff23-4f23-89ba-a11e8b610a54/jobs/11115 finishes running.

It would be great if you could give it a shot once available.
Thank you very much for your continued support!

**Comment by mumoshu** [comment] 2022-03-31 02:02
Closing this as resolved. But please feel free to reopen if it doesn't work

**Closed by mumoshu** 2022-03-31 02:02 UTC

**Comment by SohumB** [comment] 2022-04-01 05:16
My apologies for the delay. I tested this today on 0.145 and it worked great!
