### ISSUE TITLE
Selectors in combination with needs broken

### ISSUE THREAD

**Issue by pjotre86** [roboll/helmfile#2055] opened 2022-01-21 11:35 UTC
Hey!
Since version `v0.143.0` I cannot use the operation `lint`, `template`, `sync` and `apply` in combination with selectors anymore, most likely due to the changes in https://github.com/roboll/helmfile/pull/2026
To illustrate, imagine you have:
```
releases:
- name: myapp1
  chart: stable/prometheus
  needs:
  - myapp2
- name: myapp2
  chart: stable/prometheus
```
If you do a 
`helmfile template` 
everything will be fine.
But as soon as you add a selector which excludes a need of a selected release, helmfile will fail:
`helmfile -l name=myapp1 template`
will produce:
`in ./helmfile.yaml: release(s) "myapp1" depend(s) on an undefined release "myapp2". Perhaps you made a typo in "needs" or forgot defining a release named "myapp2" with appropriate "namespace" and "kubeContext"?`
The same happens with all the fore-mentioned operations. 
I assume that is not how it's intended to work, is it? Probably the needs-check introduced in v0.143.0 should not be done as soon as selectors are involved (or should be aware of them).
Partly Workaround: 
For `template`, `sync` and `apply` you can add the `--include-needs` which would then pull in the dependent releases as well and leave the needs-check satisfied, but of course that's not the same operation and `lint` doesn't support that parameter at all...

**Comment by mumoshu** [comment] 2022-01-23 11:45
@pjotre86 Hey! Thanks for reporting. Yeah, this does sound like a kind of regression.

We've previously added distinction between `--include-needs` vs `--skip-needs`, made `--skip-needs` back as the default behavior in #1835, and added `--include-transitive-needs` (#1915). So `helmfile -l name=myapp1 template` should work equivalent to `--helmfile -l name=myapp1 --skip-needs=true template`, but apparently it doesn't.
Not sure how I broke it, but yeah, probably #2026 relates.

**Comment by mumoshu** [comment] 2022-01-23 11:48
> For template, sync and apply you can add the --include-needs

What's your intended behavior?
To be clear, helmfile has never intended to include dependencies by default so what you get after the fix for this issue would still be equivalent to `helmfile -l name=myapp1 --skip-needs=true template`.

**Comment by pjotre86** [comment] 2022-01-24 19:21
Hey!
Intended behavior in case a selector is provided:

If no parameter or `--skip-needs=true` is provided -> Do not validate needs, as they won't be included in the release anyway.
If `--include-needs` or `--skip-needs=false` -> Validate the direct needs of the selected releases
If `--include-transitive-needs` is provided -> Validate the direct and transitive needs of the selected releases

Would you agree with that?

**Comment by pjotre86** [comment] 2022-01-24 19:25
For the sake of simplicity I would also be fine with skipping the needs-check in case selectors are provided.

**Comment by mumoshu** [comment] 2022-01-24 23:29
I agree with that! Thanks for your confirmation.

**Comment by bseenu** [comment] 2022-04-22 19:21
Just checking whats the status on this , when can we expect the fix for this ?

**Comment by pjotre86** [comment] 2022-04-30 05:51
I was looking into it for an hour or so, but wasn't able to fix it. Maybe I will look into it again when I have more time as this is holding us back to update helmfile at my work.

**Comment by mumoshu** [comment] 2022-04-30 06:20
@bseenu @pjotre86 Hey! I'm quite confused. Doesn't it work with `--skip-needs=true`?

**Comment by pjotre86** [comment] 2022-04-30 08:01
@mumoshu : Yes, `--skip-needs=true` works, but that renders the whole lovely dependency handling of helmfile useless. We're heavily depending on that, that's why we have to stick with 0.143 for now until this is fixed.

**Comment by mumoshu** [comment] 2022-04-30 08:10
@pjotre86 Hey! Thanks. But I'm confused- wasn't your goal to render a single release by using the selector?

> For template, sync and apply you can add the --include-needs which would then pull in the dependent releases as well and leave the needs-check satisfied, but of course that's not the same operation and lint doesn't support that parameter at all...

Or your requirement changed and you're more up to render the release along with dependencies when a selector is specified? In that case, perhaps what should be done for helmfile is to fix `helmfile-lint` to support the (skip|include)-needs flags?

**Comment by mumoshu** [comment] 2022-04-30 08:16
@pjotre86 In other words- which behavior do you want for your use-case, `--inculde-needs=true` or `--skip-needs=true`?

**Comment by pjotre86** [comment] 2022-04-30 09:45
We need both :)
In some cases you don't want to include/validate the whole dependency graph (during dev and testing mostly). In these cases we would need to add  `--skip-needs=true` to our existing tooling to keep it alive (and yes, that needs to be added to the lint-command then). I didn't do it yet, because I think it should not be necessary. I wanted to wait for a new version of helmfile, which would bring back the old (imho correct behavior). 
But if you say that it's not the intended behavior or that it's not an easy fix I would adjust our tooling.

**Comment by mumoshu** [comment] 2022-04-30 11:08
> I didn't do it yet, because I think it should not be necessary. I wanted to wait for a new version of helmfile, which would bring back the old (imho correct behavior).

@pjotre86 Ah gotcha! Then, I highly recommend you tweak your tooling. I'll fix `lint` to support those flags soon.

As far as I remember, the change originates from that some folks complained about helmfile's behavior that it isn't intuitive if it includes the dependencies or not, and conflicts on the desired default behavior of helmfile among folks. At the same time, there was a bug in selector that made it impossible for users to distinguish between missing dependencies vs undefined dependencies.

That said, the change is basically intended to encourage everyone to explicitly specify the desired behavior so that there will be no confusion anymore. Additionally, your pipeline will never break if you explicitly specified the desired behavior.

It's unfortunate that it resulted in a breaking change, but for this specific case I believe it was a good thing 🙏 

Hope this makes sense.

**Comment by mumoshu** [comment] 2022-05-01 02:58
@pjotre86 As a part of the fix https://github.com/helmfile/helmfile/pull/78 I was checking the behavior of `include-transitive-needs` (https://github.com/roboll/helmfile/pull/1983) you added. Apparently, there's no behavioral difference between include-needs and include-transitive-needs. Both seems to include transitive dependencies according to my tests 🤔 
Do you have any idea?

**Comment by mumoshu** [comment] 2022-05-01 03:11
Another finding- in your first report you shared this error message on an unselected need:

> ```
> in ./helmfile.yaml: release(s) "myapp1" depend(s) on an undefined release "myapp2". Perhaps you made a typo in "needs" or forgot defining a release named "myapp2" with appropriate "namespace" and "kubeContext"?
> ```

This seems like another bug in how helmfile-template. The correct error message, in that case, should be something like:

```
in ./helmfile.yaml: release "default/default/myapp" depends on "default/default/myapp" which does not match the selectors. Please add a selector like "--selector name=myapp", or indicate whether to skip (--skip-needs) or include (--include-needs) these dependencies
```

**Comment by pjotre86** [comment] 2022-05-01 08:56
Great!  
I guess I can work with this, will try out next week and close this issue if I succeed.  
Thanks for the patience and diligence, I'm glad we came to terms with this.  
Thanks a lot!

**Closed** 2022-06-19 22:19 UTC
Labels: bug
