### ISSUE TITLE
`strategicMergePatches` seems to blind `helmfile deps` to the existence of this repository

### ISSUE THREAD

**Issue by SohumB** [roboll/helmfile#2110] opened 2022-03-21 06:37 UTC
If you have a helmfile with a remote repository, such that `helmfile deps` creates a helmfile.lock containing that resolved repository, and then you add a `strategicMergePatches` to the corresponding release, then run `helmfile deps` again, the repository gets removed from the lockfile.

**Comment by mumoshu** [comment] 2022-03-21 23:14
@SohumB That's expected behavior. `helmfile` needs to render your chart as K8s manifests first, so that it can apply various patches including `strategicMergePatches`. Once it's rendered, dependencies originally included in `Chart.yaml` and `Chart.lock` has already been merged to the resulting K8s manifests hence no more available as chart dependencies.

**Comment by mumoshu** [comment] 2022-03-21 23:14
What was your real issue though? 🤔

**Comment by SohumB** [comment] 2022-03-21 23:20
I see. In that case the real issue is that `helmfile sync` and `helmfile apply` both error under that configuration, with this message:

```
in ./helmfile.yaml: [no resolved dependency found for "[...]", running "helmfile deps" may resolve the issue]
```

**Comment by mumoshu** [comment] 2022-03-21 23:32
@SohumB Thanks! What are included in `[...]`? Chart dependencies listed in the original `Chart.yaml`?

**Comment by SohumB** [comment] 2022-03-21 23:40
Chart dependencies listed under `releases`, so `foo` in the tiny example above.

**Comment by mumoshu** [comment] 2022-03-21 23:46
@SohumB Thank you! Last question, which method does your chart `foo` use for listing chart dependencies, `Chart.yaml` or `requirements.yaml`?

**Comment by SohumB** [comment] 2022-03-22 00:01
`Chart.yaml`. If you want to have a look at the specific example we hit the problem on, it's `robusta` 0.9.4 available at https://robusta-charts.storage.googleapis.com.

**Comment by mumoshu** [comment] 2022-03-22 00:49
@SohumB Thank you! I was recently fixing a few issues found in `chartify` which Helmfile uses internally to provided this feature. https://github.com/variantdev/chartify

I'll definitely investigate this before cutting the next release of chartify.

**Comment by mumoshu** [comment] 2022-03-23 01:48
@SohumB Hey! I tried to reproduce your issue with the robusta chart but still have no luck so far.
Did `helmfile template` work while `sync` and `apply` fail?

**Comment by SohumB** [comment] 2022-03-23 02:02
Is that so? My apologies, I thought I'd cut down my testcase to a repro, but apparently not. I'll investigate further and report back.

**Comment by SohumB** [comment] 2022-03-27 22:29
Here we go. It seems just running a helmfile with the repository being blinded does not trigger the issue, because in that case `helmfile` does not create a lockfile, which means `helmfile template` later doesn't make the assumption that all dependencies are in the lockfile. This works:

```shell
$ cat helmfile.yaml
repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: robusta
  url: https://robusta-charts.storage.googleapis.com

releases:
  - name: robusta
    chart: robusta/robusta
    values:
      - clusterName: test # robusta requires this to render
    strategicMergePatches:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: robusta-forwarder
        spec:
          template:
            spec:
              nodeSelector:
                kubernetes.io/arch: amd64
  - name: prometheus
    chart: stable/prometheus
$ helmfile deps
Adding repo stable https://charts.helm.sh/stable
"stable" has been added to your repositories

Adding repo robusta https://robusta-charts.storage.googleapis.com
"robusta" has been added to your repositories

Updating dependency /tmp/sohum/chartify145530727/robusta/robusta
Updating dependency /tmp/sohum/2520405854
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "robusta" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading prometheus from repo https://charts.helm.sh/stable
Deleting outdated charts
$ helmfile template 
Adding repo stable https://charts.helm.sh/stable
"stable" has been added to your repositories

Adding repo robusta https://robusta-charts.storage.googleapis.com
"robusta" has been added to your repositories

in ./helmfile.yaml: [no resolved dependency found for "robusta", running "helmfile deps" may resolve the issue]
```

**Comment by mumoshu** [comment] 2022-03-28 01:53
@SohumB Thanks! I was still unable to reproduce it with the latest version of Helmfile using your helmfile.yaml. What's your helmfile version?

**Comment by SohumB** [comment] 2022-03-28 02:09
I was on 0.143.0, but I'm getting the same output on 0.143.4.

**Comment by mumoshu** [comment] 2022-03-28 02:32
@SohumB Thanks. Would you mind sharing your helmfile.lock if it already exists?

**Comment by SohumB** [comment] 2022-03-28 02:34
Sure — it's exactly what you'd expect. 
```yaml
version: v0.143.4
dependencies:
- name: prometheus
  repository: https://charts.helm.sh/stable
  version: 11.12.1
digest: sha256:a5158f1361f2bbc4e73a80a22dd92b44538bdebeb2419658c36e31aa603b05fd
generated: "2022-03-28T13:08:03.696305857+11:00"
```

**Comment by mumoshu** [comment] 2022-03-30 04:13
@SohumB Hey! Just confirming, but are you sure you reran `helmfile deps` after adding `robusta` release to your helmfile.yaml?

`helmfile.lock` is there to make helmfile runs reproducible. If you run `helmfile deps` once, you'd need to rerun `helmfile deps` every time you add a new dependency(i.e. new chart referenced from within your release in helmfile.yaml). Otherwise you get errors like that, due to helmfile's kindness :)

**Comment by mumoshu** [comment] 2022-03-30 04:15
Rereading your original report- so 

> run helmfile deps again, the repository gets removed from the lockfile.

does this mean `helmfile deps` removed the `robust` dependency from helmfile.lock?

**Comment by SohumB** [comment] 2022-03-30 04:27
That is correct, yes. 

* robusta is in repositories and releases → `helmfile deps` adds `robusta` to the lockfile
* as above, but add `strategicMergePatches` → `helmfile deps` removes `robusta` from the lockfile

**Comment by mumoshu** [comment] 2022-03-30 04:30
@SohumB Thank you for your confirmation! I believe that's enough information for me to track down the cause. Let me see what's going on

**Comment by mumoshu** [comment] 2022-06-05 08:52
Fixed via https://github.com/helmfile/helmfile/pull/23

**Closed by mumoshu** 2022-06-05 08:52 UTC
Labels: bug
