### ISSUE TITLE
chart with go-getter bugs with template cmd

### ISSUE THREAD

**Issue by itscaro** [roboll/helmfile#1847] opened 2021-05-12 23:48 UTC
with

```
# helmfile.yaml
releases:
- name: pinpoint
  chart: git::https://github.com/pinpoint-apm/pinpoint-kubernetes.git@pinpoint?ref=master
```

runing `template` results in this error

```
.helmfile\cache\pinpoint\https_github_com_pinpoint-apm_pinpoint-kubernetes_git.ref=master\pinpoint
  Error: found in Chart.yaml, but missing in charts/ directory: mysql, hdfs, zookeeper
  helm.go:81: [debug] found in Chart.yaml, but missing in charts/ directory: mysql, hdfs, zookeeper
  helm.sh/helm/v3/pkg/action.CheckDependencies
```

I saw this https://github.com/roboll/helmfile/pull/1408 but I haven't had time to look into closely.

Note to self:
![image](https://user-images.githubusercontent.com/266018/118058317-3b817580-b38e-11eb-9b31-4f7fa534431e.png)

**Comment by mumoshu** [comment] 2021-05-12 23:55
@itscaro Thanks for reporting. This does sound like a bug. We do use `go-getter` internally to fetch the chart and use it as if it was a local chart.

In that case, I thought, any helmfile command should result in running `helm dep build`, which downloads those `mysql`, `hdfs`, and `zookeeper` dependencies.
Maybe it's not working as expected?

**Comment by itscaro** [comment] 2021-05-13 00:06
@mumoshu I will investigate this tomorrow or this weekend, will tell you if I find something.

**Comment by itscaro** [comment] 2021-05-15 12:01
@mumoshu The test to skip deps seems buggy, for go-getter-fetched charts should they be considered local?

![image](https://user-images.githubusercontent.com/266018/118359977-f889f280-b585-11eb-9b92-bbcb202b167b.png)

**Comment by mumoshu** [comment] 2021-05-16 00:29
@itscaro Thanks. That's actually a good catch!

I think you are almost correct. But what seems important here would be to differentiate the needs to run `helm dep up` and `helm dep build` respectively.

Currently, a local chart generated by using go-getter always results in skipping `helm dep up` and `helm dep build` altogether, which makes your case failing.

Previously, we were running both helm commands, so your issue didn't occur. However, it resulted in #1547 instead, which was fixed by #1548.

So just letting it run `helm dep up` and `build` on your case brings back #1547, which isn't what we want.

Probably we let chartify only skip `helm dep up`, so that helmfile will work on both yours and the linkerd chart mentioned in #1547?

**Comment by mumoshu** [comment] 2021-05-16 04:06
@itscaro Ah sorry, I realized you aren't using `chartify` at all. Then, specifically fixing your issue should be possible just by changing the `!isLocal` part to `(!isLocal && !chartFetchedByGoGetter)`, so that it runs `helm dep build` when the chart if fetched by ge-getter.

**Comment by mumoshu** [comment] 2021-05-16 04:17
It turns out even `helm dep build` fails on the linkerd2 chart.

Perhaps we can just treat the linkerd chart as broken and make it a special case?


```
$ helm repo add linkerd https://helm.linkerd.io/stable
$ helm fetch linkerd/linkerd2 --version 2.8.1 
$ tar zxvf linkerd2-2.8.1.tgz
$ helm dep up linkerd2
Error: directory partials not found
$ helm dep build linkerd2
Error: directory partials not found
```

**Comment by mumoshu** [comment] 2021-05-16 04:26
Read https://github.com/roboll/helmfile/pull/1548 a bit more, and this turns out to be a regression introduced there.

Apparently, I only intended to make it possible to opt-out running `helm dep up/build` by `skipDeps: true` in https://github.com/roboll/helmfile/pull/1548, but the bug in `skipDeps` you pointed out resulted in you can't run `dep up/build` at all on a chart fetchded by go-getter.

**Closed** 2021-05-16 04:43 UTC
