### ISSUE TITLE
Using go-getter for chart with ref to commit id fails

### ISSUE THREAD

**Issue by kirrmann** [roboll/helmfile#2106] opened 2022-03-16 11:43 UTC
Using a go-getter for the chart with ref set to a commid id fails in newer versions of helmfile

config:
```
releases:
  - name: cronjobs
    namespace: cronjobs
    chart: git::https://github.com/bambash/helm-cronjobs.git@.?ref=8b7377f12fac660e7f565d0b8301ce39c3e74df0
    values:
      - values.yaml
```
     
Fails in helmfile v0.143.1 with error:
```
in ./helmfile.yaml: [release "cronjobs": fetching "git::https://github.com/bambash/helm-cronjobs.git@?ref=8b7377f12fac660e7f565d0b8301ce39c3e74df0": get: error downloading 'https://github.com/bambash/helm-cronjobs.git?ref=8b7377f12fac660e7f565d0b8301ce39c3e74df0': /opt/homebrew/bin/git exited with 128: Cloning into '/Users/foobar/Library/Caches/helmfile/cronjobs/admin.k8s.comvel.cloud/cronjobs/https_github_com_bambash_helm-cronjobs_git.ref=8b7377f12fac660e7f565d0b8301ce39c3e74df0'...
fatal: Remote branch 8b7377f12fac660e7f565d0b8301ce39c3e74df0 not found in upstream origin
]
```

but works in version v0.141.0 flawlessly 

The commit does exist https://github.com/bambash/helm-cronjobs/commit/8b7377f12fac660e7f565d0b8301ce39c3e74df0

**Comment by mumoshu** [comment] 2022-04-05 01:10
Thanks for reporting!
It needs verification from anyone, but I'm now wondering if this is due to a regression in go-getter(helmfile uses it internally) that is fixed in go-getter 1.5.10 https://github.com/hashicorp/go-getter/releases/tag/v1.5.10

**Comment by mumoshu** [comment] 2022-04-06 02:42
Seems so

```
$ git diff v0.141.0...v0.143.1 go.sum | grep go-getter
-github.com/hashicorp/go-getter v1.5.0 h1:ciWJaeZWSMbc5OiLMpKp40MKFPqO44i0h3uyfXPBkkk=
-github.com/hashicorp/go-getter v1.5.0/go.mod h1:a7z7NPPfNQpJWcn4rSWFtdrSldqLdLPEF3d8nFMsSLM=
+github.com/hashicorp/go-getter v1.5.9 h1:b7ahZW50iQiUek/at3CvZhPK1/jiV6CtKcsJiR6E4R0=
+github.com/hashicorp/go-getter v1.5.9/go.mod h1:BrrV/1clo8cCYu6mxvboYg+KutTiFnXjMEgDD8+i7ZI=
```

Let's upgrade it and see if it actually fixes the issue

**Comment by mumoshu** [comment] 2022-04-19 22:54
I'm closing this as resolved but please feel free to create another issue if it reproduces.

**Closed by mumoshu** 2022-04-19 22:54 UTC

**Comment by kirrmann** [comment] 2022-04-20 07:44
Is this already released? Doesn't seem like it's in 0.144.0

**Comment by mumoshu** [comment] 2022-04-20 08:10
@kirrmann You need to built the edge version of helmfile from the main branch of `helmfile/helmfile`(our new home)

**Comment by kirrmann** [comment] 2022-04-20 10:59
thanks. I just tried it and it works perfectly now 👍
