### ISSUE TITLE
Helmfile with many releases is too slow due to "Building dependency" etc

### ISSUE THREAD

**Issue by max-rocket-internet** [roboll/helmfile#959] opened 2019-11-12 10:54 UTC
Currently we have around 350 releases in our helmfile but the problem is that when we run helmfile with a specific selector, it simply takes too long with messages like this:

```
Building dependency release=eu01-ldt01-app1, chart=../charts/apps/app1
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "anchore" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
Saving 1 charts
Downloading prometheus-redis-exporter from repo https://kubernetes-charts.storage.googleapis.com/
Deleting outdated charts

Building dependency release=eu01-ldt01-app2, chart=../charts/apps/app2
No requirements found in ../charts/apps/app2/charts.

Building dependency release=eu01-ldt01-courier-service, chart=../charts/apps/courier-service
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "anchore" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
Saving 1 charts
Downloading prometheus-postgres-exporter from repo https://kubernetes-charts.storage.googleapis.com/
Deleting outdated charts

Building dependency release=eu01-ldt01-app5, chart=../charts/apps/app5
No requirements found in ../charts/apps/app5/charts.

Building dependency release=eu01-ldt01-app4, chart=../charts/apps/app4
No requirements found in ../charts/apps/app4/charts.

Building dependency release=eu01-ldt01-app3, chart=../charts/apps/app3
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "anchore" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
Saving 5 charts
Downloading prometheus-redis-exporter from repo https://kubernetes-charts.storage.googleapis.com/
Downloading prometheus-rabbitmq-exporter from repo https://kubernetes-charts.storage.googleapis.com/
Downloading prometheus-postgres-exporter from repo https://kubernetes-charts.storage.googleapis.com/
Downloading prometheus-postgres-exporter from repo https://kubernetes-charts.storage.googleapis.com/
Downloading prometheus-postgres-exporter from repo https://kubernetes-charts.storage.googleapis.com/
Deleting outdated charts
```

How can I make helmfile ignore all release that do not match the selector?

**Comment by max-rocket-internet** [comment] 2019-11-12 11:46
If I use 2 selectors like this that match a single release:

```
helmfile --selector app=prometheus-exporter-cloudwatch,cluster=cluster1 --file main.yaml apply
```

Or if I just specify the exact release name:

```
helmfile --selector name=my-release-1 --file main.yaml apply
```

Both are still doing `Building dependency` for every single release.

**Comment by mumoshu** [comment] 2019-11-13 00:42
@max-rocket-internet Thanks for reporting! Ah, and probably this started happening since very recent versions of helmfile?

If so, this seems like a regression since v0.90.0.

**Comment by jim-barber-he** [comment] 2019-11-13 00:52
I was going to raise a similar bug report, but this is close enough that I may as well add to it.
Things for me are working fine in version `0.90.5` but version `0.90.6` through to `0.90.8` all have the dependency building problem for me.

In my case we have some parallel helmfile deploys happening using the same repository that has many releases defined in the one `helmfile.yaml` file.
They are all using selectors but every single one goes through sorting out dependencies for releases that aren't selected.

In our case, when a chart of a non-selected release has its own dependencies in its `requirements.yaml` file, parallel deploys fail due to only one of them being able to create and use a `tmpchart` directory (I think that's the name, I'm going by memory here) while the others encounter that the directory already exists and fail.

**Comment by mumoshu** [comment] 2019-11-13 01:10
@jim-barber-he Thanks! You are correct. This might not be since v0.90.0 but v0.90.5, maybe #924 

> In our case, when a chart of a non-selected release has its own dependencies in its `requirements.yaml` file, parallel deploys fail due to only one of them being able to create and use a `tmpchart` directory (I think that's the name, I'm going by memory here) while the others encounter that the directory already exists and fail.

I'm unsure if I'm understanding this part correctly.

Maybe `tmpchart` is the name of temporary directory that `helmfile` creates in order to run `helm dep build` against that `requirements.yaml`?

If so, I'm not sure how it interfere with "parallel deploys" you mention, as the dependency buliding happens sequentially and it happens before deployments(=phased parallel `helm upgrade`s).

**Comment by jim-barber-he** [comment] 2019-11-13 01:12
I could reproduce and show the exact symptoms if you like.
But in the end it all stems from having dependencies for non-selected charts all being done and if you have multiple helmfile processes running at the same time, these can clash with each other because of the temporary directories they create when working with charts that have dependent charts.

**Comment by mumoshu** [comment] 2019-11-13 01:20
@jim-barber-he Thanks! Seems like something unknown to me is happening.

I'd definitely appreciate it if you could share anything that helps me to allow reproduce it locally, so I can debug, fix, and add regression tests for it.

**Comment by jim-barber-he** [comment] 2019-11-13 09:51
Ok I'll see what I can do tomorrow. Work got super hectic today and I couldn't find the time to reproduce the problem again.

**Comment by max-rocket-internet** [comment] 2019-11-13 10:28
> I'd definitely appreciate it if you could share anything that helps me to allow reproduce it locally

I think it's as simple running `helmfile apply` with a selector will run the dependency stuff for charts that are not matched by the selector. Or is it not that simple?

**Comment by mumoshu** [comment] 2019-11-13 23:19
@max-rocket-internet For your issue, yes. But I don't think simple `helmfiel apply` run results in the temp directory errors like @jim-barber-he has encountered.

**Comment by jim-barber-he** [comment] 2019-11-14 07:33
Here's a more complete description of the issue I encountered.

We have a setup script for local development environments that allows developers to deploy the applications that they want.
Each application chosen is deployed in parallel by starting a Docker image that contains helm, helmfile, and so on, and mounting the local helmfile.yaml and charts into it.
That image after doing things like populating the environment with secrets ends up running the following command:
```
helmfile --selector app=$APP_LABEL apply --args "--debug"
```
Where `$APP_LABEL` is the name of the application chosen and the helmfile contains that label against appropriate chart(s).

We have a chart in the repo with a `requirements.yaml` file like so:
```
$ cat helm_charts/prometheus-to-cloudwatch/requirements.yaml
dependencies:
- name: common
  version: 0.0.4
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/

```

It's not something we've deployed for a long time, and really should it should be deleted from our repository.
However it is what triggered our problems.

The first problem being that our `helmfile.yaml` now longer has the incubator repository defined in it.
Even though we were deploying applications other than `prometheus-to-cloudwatch` we were presented with the following error in the deployment pods:
```
in ./helmfile.yaml: helm exited with status 1:
  Error: no repository definition for https://kubernetes-charts-incubator.storage.googleapis.com/. Please add the missing repos via 'helm repo add'
```

That's easily fixed by adding the incubator repository to `helmfile.yaml` even though we shouldn't need to because none of our other charts use it.

After adding the incubator repository, the next problem is that when we are deploying more than one chosen application, we spin up multiple deployment pods in parallel, all mounting the local charts into them.
One of these will work and deploy the application.
The others fail with:
```
in ./helmfile.yaml: helm exited with status 1:
  Error: Unable to move current charts to tmp dir: rename helm_charts/prometheus-to-cloudwatch/charts helm_charts/prometheus-to-cloudwatch/tmpcharts: file exists
```

Again this is despite not having chosen `prometheus-to-cloudwatch` to be deployed.

With `0.90.5` this issue doesn't happen, but does for 0.90.6 through to `0.90.8`

Hopefully the description above has enough detail for what is going wrong when dependencies are being done for charts we are not trying to install?

**Comment by mumoshu** [comment] 2019-11-14 07:37
@jim-barber-he Thanks a lot for the detailed report!

To be extra clear - was it working on pre v0.90.0 e.g. v0.89.x?

**Comment by mumoshu** [comment] 2019-11-14 07:41
So the error is coming from helm itself, right?

https://github.com/helm/helm/blob/9be2445da5dce57316a8c9fbc07823e7ea017abf/pkg/downloader/manager.go#L202

I'm not sure how it's supposed work at all when run concurrently.

>  when we are deploying more than one chosen application, we spin up multiple deployment pods in parallel, all mounting the local charts into them.

You mean that you're concurrently running multiple helmfile containers mounting the same directories, or anything else?

**Comment by jim-barber-he** [comment] 2019-11-14 07:52
> To be extra clear - was it working on pre v0.90.0 e.g. v0.89.x?

I don't know, but I could test for you. I know that it works for `0.90.5` but not for anything later than that.

> You mean that you're concurrently running multiple helmfile containers mounting the same directories, or anything else?

Yes concurrently running multiple helmfile pods (it in Minikube) mounting the same directory that has the helmfile.yaml and the charts in it.
But each container is running a different helmfile command.
E.g.
Pod1 is running `helmfile --selector app=app1 apply --args "--debug"`
Pod2 is running `helmfile --selector app=app2 apply --args "--debug"`
Pod3 is running `helmfile --selector app=app3 apply --args "--debug"`
and so on...
But none of those apps use the chart which is throwing the error above.

**Comment by mumoshu** [comment] 2019-11-14 08:07
> But none of those apps use the chart which is throwing the error above.

Got it! Once `--selector` is fixed to work as expected(which closes this issue), it won't fail anymore.

Just curious, but you'll never run `helmfile` without `--selector` in the future, right? If you do that, I think you'll start to see the error again, even after this regression is fixed.

To fully avoid it, I'd suggest making it sequential. I believe what you have now is something like the below:

```
releases:
- name: app1
  chart: same/local/chart
- name: app2
  chart: same/local/chart
- name: app3
  chart: same/local/chart
```

If you could rewrite it to:

```
releases:
- name: app1
  chart: same/local/chart
- name: app2
  chart: same/local/chart
  needs:
  - app1
- name: app3
  chart: same/local/chart
  needs:
  - app2
```

you'll never see th error due to that upstream issue.

**Comment by jim-barber-he** [comment] 2019-11-14 08:13
> Got it! Once --selector is fixed to work as expected(which closes this issue), it won't fail anymore.

Correct, that's what I added my detail to this issue. I fully expect the problem to go away once dependencies only happen for the charts being selected.

> Just curious, but you'll never run helmfile without --selector in the future, right? If you do that, I think you'll start to see the error again, even after this regression is fixed.

No, if we were to, then it would be in a single helmfile run which would just do the dependencies once though right?

> To be extra clear - was it working on pre v0.90.0 e.g. v0.89.x?

I tried this with `0.89.0` and that worked without issue too.
It seems it broke in `0.90.6`

**Comment by mumoshu** [comment] 2019-11-14 09:08
> No, if we were to, then it would be in a single helmfile run which would just do the dependencies once though right?

Not really, I think. Each helmfile process runs `helm dep build` once because they have no way to know whether another concurrent process has done it or not.

I believe the permanent fix here would be Helmfile changed to copy the local chart to random location before `helm dep build`, or fix in the upstream.

**Comment by mumoshu** [comment] 2019-11-14 10:16
> I tried this with 0.89.0 and that worked without issue too.

Thanks a lot for your help! That makes sense.

**Closed** 2019-11-14 11:57 UTC

**Comment by mumoshu** [comment] 2019-11-14 11:59
Could you try v0.90.9 which includes the fix #964?

**Comment by max-rocket-internet** [comment] 2019-11-14 12:32
The new release works for me. Thanks @mumoshu 💖

**Comment by jim-barber-he** [comment] 2019-11-15 00:57
I've also just tried `0.90.9` and also the latest `0.92.0` and both are working.
